version: "3.7"

services:
  workspace:
    &workspace
    image: khs1994/php:7.3.10-cli-alpine
    networks:
      - backend
    volumes:
      - vscode-server:/root/.vscode-server
      - phpls-cache:/root/.phpls
      # fix me
      - ./:/app/demo
      # fix me 将依赖挂载到数据卷
      - vendor:/app/demo/vendor
      - type: volume
        source: composer_cache-data
        target: /tmp/cache
    command: /bin/sh -c "cp $$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini.default $$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini ; while sleep 1000; do :; done"
    environment:
      APP_ENV: development

  composer:
    << : *workspace
    restart: "no"
    image: "khs1994/php:7.3.10-composer-alpine"
    # fix me
    working_dir: /app/demo
    command: [] # install | update

networks:
  backend:
    external: true
    name: lnmp_backend

volumes:
  composer_cache-data:
    external: true
    name: lnmp_composer_cache-data
  vscode-server:
  phpls-cache:
  vendor:
    # 或者复用其他数据卷
    # external: true
    # name: lnmp_laravel_vendor
