on:
  push:
    branches:
    - master
  # pull_request:
  # tags:
  # paths:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '*/15 * * * *'

name: CI

jobs:
  test:
    strategy:
      matrix:
        php: ["7.2.1","7.3.8"]
    runs-on: ubuntu-latest
    # needs: job
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: install
        uses: docker://khs1994/php:7.2.21-composer-alpine
        with:
          args: bash -c "php .pcit.php ; composer install -q --ignore-platform-reqs"
      - name: script
        uses: docker://khs1994/php:7.2.21-fpm-alpine
        env:
          PHP_VERSION: ${{ matrix.php }}
        with:
          args: |
            bash -c "mv ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini.default ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini
            ; echo ${PHP_VERSION}
            ; sleep 30
            ; mysql -uroot -pmytest -e \"show databases\"
            ; composer test:coverage"
      - name: after_success
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash)
        if: success()
      - name: after_failure
        run: echo "build error"
        if: failure()
      - name: always
        run: |
          echo "run always"
          pwd
        if: always()
        working-directory: /

    services:
      mysql:
        image: mysql:8.0.11
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: mytest
        volumes:
          - mysql-data:/var/lib/mysql
        options: --cpus 1
