on:
  push:
    branches:
    - master
  # pull_request:
  # tags:
  # paths:
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '*/15 * * * *'

name: CI

jobs:
  test:
    strategy:
      matrix:
        php_version: ["7.2.21","7.3.8"]
    runs-on: ubuntu-latest
    # needs: job
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: install
        uses: docker://khs1994/php:7.2.21-composer-alpine
        with:
          args: |
            bash -c "php .pcit.php \
            ; composer install -q --ignore-platform-reqs"
      - name: script
        uses: khs1994-docker/actions-setup-php@master
        with:
          php_version: ${{ matrix.php_version }}
          args: |
            bash -c "mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.default \
                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
            ; php -v \
            ; env \
            ; sleep 30 \
            ; vendor/bin/phpunit --coverage-clover=coverage.xml"
      - name: after_success
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          mysql -uroot -pmytest -P 13306 -e "show databases"
          bash <(curl -s https://codecov.io/bash)
        if: success()
      - name: after_failure
        run: echo "build error"
        if: failure()
      - name: always
        run: |
          echo "run always"
          pwd
        if: always()
        working-directory: /

    services:
      mysql:
        image: mysql:8.0.11
        ports:
          - 13306:3306
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: mytest
        volumes:
          - mysql-data:/var/lib/mysql
        options: --cpus 1 -v mysql-data:/var/lib/mysql
